import * as THREE from 'three'
export default [
  {
    name: 'Classic',
    length: 7,
    palette: [ 
      new THREE.Color("#000000").convertLinearToSRGB(), 
      new THREE.Color("#14213d").convertLinearToSRGB(),
      new THREE.Color("#47b8f0").convertLinearToSRGB(),
      new THREE.Color("#e5e5e5").convertLinearToSRGB(),
      new THREE.Color("#fca311").convertLinearToSRGB(),
      new THREE.Color("#bb3c11").convertLinearToSRGB(),
      new THREE.Color("#000000").convertLinearToSRGB(), 
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0)
    ],
  },
  {
    name: 'Sunny Beach Day',
    length: 5,
    palette: [
      new THREE.Color("#264653").convertLinearToSRGB(), 
      new THREE.Color("#2a9d8f").convertLinearToSRGB(),
      new THREE.Color("#e9c46a").convertLinearToSRGB(),
      new THREE.Color("#f4a261").convertLinearToSRGB(),
      new THREE.Color("#e76f51").convertLinearToSRGB(),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0)
    ],
  },
  {
    name: 'Autumn',
    length : 6,
    palette: [ 
      new THREE.Color("#335c67").convertLinearToSRGB(),
      new THREE.Color("#99a88c").convertLinearToSRGB(),
      new THREE.Color("#fff3b0").convertLinearToSRGB(),
      new THREE.Color("#e09f3e").convertLinearToSRGB(),
      new THREE.Color("#9e2a2b").convertLinearToSRGB(),
      new THREE.Color("#540b0e").convertLinearToSRGB(),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0)
    ],
  },
  {
    name: 'Watermelon',
    length: 5,
    palette: [
      new THREE.Color("#ef476f").convertLinearToSRGB(),
      new THREE.Color("#ffd166").convertLinearToSRGB(),
      new THREE.Color("#06d6a0").convertLinearToSRGB(),
      new THREE.Color("#118ab2").convertLinearToSRGB(),
      new THREE.Color("#073b4c").convertLinearToSRGB(),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0)
    ],
  },
  {
    name: 'Pastel Rainbow',
    length: 9,
    palette: [
      new THREE.Color("#ffadad").convertLinearToSRGB(), 
      new THREE.Color("#ffd6a5").convertLinearToSRGB(),
      new THREE.Color("#fdffb6").convertLinearToSRGB(),
      new THREE.Color("#caffbf").convertLinearToSRGB(),
      new THREE.Color("#9bf6ff").convertLinearToSRGB(),
      new THREE.Color("#a0c4ff").convertLinearToSRGB(),
      new THREE.Color("#bdb2ff").convertLinearToSRGB(),
      new THREE.Color("#ffc6ff").convertLinearToSRGB(),
      new THREE.Color("#fffffc").convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
    ],
  },
  {
    name: 'Black and White',
    length: 2,
    palette: [
      new THREE.Color(0,0,0), 
      new THREE.Color(1,1,1),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
      new THREE.Color(0,0,0),
    ],
  },
  {
    name: 'Oceanic Cactus',
    length: 5,
    palette: [
      new THREE.Color("#1a535c").convertLinearToSRGB(), 
      new THREE.Color("#4ecdc4").convertLinearToSRGB(),
      new THREE.Color("#f7fff7").convertLinearToSRGB(),
      new THREE.Color("#ff6b6b").convertLinearToSRGB(),
      new THREE.Color("#ffe66d").convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
      new THREE.Color(0,0,0).convertLinearToSRGB(),
    ],
  },
]
